echo "apt-get install rsyslog tree -y" 
echo " !!!B file /etc/rsyslog.d/00_common.conf pishem!!!"
echo 'module(load="imtcp")'
echo 'module(load="imuxsock")'
echo 'module(load="imjournal")'
echo "authpriv.* /var/log/auth.log"
echo 'input(type="imtcp" port="514")'
echo "if $fromhost-ip contains '192.168.0.62' then {"
echo "*.warn /opt/hq-rtr/router.log"
echo "}"
echo "if $fromhost-ip contains '10.5.5.2' then {"
echo "*.warn /opt/br-rtr/router.log"
echo "}"
echo "if $fromhost-ip contains '192.168.1.1' then {"
echo "*.warn /opt/br-srv/server.log"
echo "}"
echo "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
echo "nano /etc/rsyslog.d/00_common.conf"
echo "systemctl enable --now rsyslog && mkdir -p /opt/br-rtr && mkdir -p /opt/hq-rtr && mkdir -p /opt/br-srv"
echo "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
echo " Na hq-rtr,br-rtr,br-srv v file 00_common.conf"
echo " Pishi 1 stroky"
echo "*.warn @@192.168.0.1:514"
echo " Zatem"
echo "systemctl enable --now rsyslog"
echo "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
echo " Zahodim v file /etc/logrotate.conf na hq-srv"
echo " Privodim k takomy vidy, !!!pishem tol'ko DIREKTORII, MINSIZE 10M, i SKOBOCHKI {}!!!"
echo "/opt/hq-rtr/*.log"
echo "/opt/br-rtr/*.log"
echo "/opt/br-srv/*.log"
echo "{"
echo "minsize 10M"
echo "weekly"
echo "rotate 4"
echo "create"
echo "compress"
echo "}"
echo "nano /etc/logrotate.conf"
echo "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
echo "systemctl enable --now logrotate"
echo " Proverka=logrotate -d /etc/logrotate.conf"
echo " Proverka=tree /opt/"